config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#tirage'

  get 'pages/resultat'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lot.rb
class Lot < ApplicationRecord

  #Validations
  validates :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def tirage
    @number = Lot.all.count
  end

  def resultat
    @lots = Lot.all
    @lot = Lot.all.sample
    Lot.delete(@lot.id) unless @lot.id == 1
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tombola</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/resultat.html.erb
<div class="container">
  <%= image_tag("logo_baco.png", :alt => "logo baco", :id => "logo_baco") %>
  <% if @lots.length == 0 %>
    <h2>Vous gagnez le dernier lot de ce tournoi :</h2>
  <% else %>
    <h2>Félicitation, vous gagnez :</h2>
  <% end %>
  <h1>
    <%= @lot.name %>
  </h1>
  <% if @lots.length == 0 %>
    <h2>Merci pour votre participation 2023 et à l'année prochaine !</h2>
  <% else %>
    <%= link_to "REJOUER", root_path, class: "bouton" %>
  <% end %>
</div>

app/views/pages/tirage.html.erb
<div class="container">
  <%= image_tag("logo_baco.png", :alt => "logo baco", :id => "logo_baco") %>
  <h1>Jouer à la tombola du Bacosun</h1>
  <%= link_to "TIRAGE", pages_resultat_path, class: "bouton" %>
  <p>Il ne reste plus que
    <%= @number %> lots à gagner !
  </p>
</div>